apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: gkwmiddelkamp/vault
    newName: gkwmiddelkamp/vault
    newTag: latest
resources:
  - secret.yaml
  - deployment.yaml
  - service.yaml