apiVersion: v1
kind: Service
metadata:
  labels:
    app: vault
  name: vault
spec:
  ports:
    - name: api
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: vault
  type: ClusterIP